version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13.1

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      
      - run: make test