version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.1
    working_directory: ~/go-guardian
    steps:
      - checkout
      - run: make install
      - run: make lint
      - run: make cover
      - run: make deploy-cover
      - run: make bench
      - run: make release

